/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  browserHistory,
  hashHistory,
} from 'react-router';
import { Provider } from 'react-redux';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import RoleEditPage from './pages/RoleEditPage';
import RoleListPage from './pages/RoleListPage';
import CategoryEditPage from './pages/CategoryEditPage';
import CategoryListPage from './pages/CategoryListPage';
import AdvEditPage from './pages/AdvEditPage';
import AdvListPage from './pages/AdvListPage';
import UserManagePage from './pages/UserManagePage';
import GoodListPage from './pages/GoodListPage';
import GoodEditPage from './pages/GoodEditPage';
import UserEditPage from './pages/UserEditPage';
import UserAuthority from './pages/UserAuthority';
import UserRegister from './pages/UserRegister';
import Company from './pages/Company';
import Banner from './pages/Banner';
import BannerList from './pages/BannerList';
import ActivityList from './pages/ActivityList';
import ActivityClass from './pages/ActivityClass';
import ActivityClassList from './pages/ActivityClassList';
import Setting from './pages/Setting';
import BlankLayout from './layouts/BlankLayout';
import AuthRoute from './components/AuthRoute';
import Login from './pages/Login';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import Activity from './pages/Activity';
import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout';
import Home from './pages/Home';
import HeaderFooterLayout from './layouts/HeaderFooterLayout';
import NotFound from './pages/NotFound';
import ComLoading from './util/util';
const autoGeneratedRoutes = [{
  path: 'roleEditPage/:id',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: RoleEditPage
  }
}, {
  path: 'roleListPage',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: RoleListPage
  }
}, {
  path: 'categoryEditPage/:id',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CategoryEditPage
  }
}, {
  path: 'categoryListPage',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CategoryListPage
  }
}, {
  path: 'advEditPage',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AdvEditPage
  }
}, {
  path: 'advListPage',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AdvListPage
  }
}, {
  path: 'userManagePage',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserManagePage
  }
}, {
  path: 'goodListPage',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: GoodListPage
  }
}, {
  path: 'goodEditPage/:id',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: GoodEditPage
  }
}, {
  path: 'userEditPage/:id',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserEditPage
  }
}, {
  path: 'userAuthority',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserAuthority
  }
}, {
  path: 'userRegister',
  childRoutes: [],
  component: BlankLayout,
  indexRoute: {
    component: UserRegister
  }
}, {
  path: 'company/:id',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Company
  }
}, {
  path: 'activityList',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ActivityList
  }
}, {
  path: 'activityClassList/:pid',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ActivityClassList
  }
}, {
  path: 'activityClass/:activityClassId/:pid',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ActivityClass
  }
}, {
  path: 'Setting',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Setting
  }
}, {
  path: 'Login',
  childRoutes: [],
  component: BlankLayout,
  indexRoute: {
    component: Login
  }
}, {
  path: 'Home',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Home
  }
}, {
  path: 'activity/:activityId',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Activity
  }
}, {
  path: 'banner/:activityId',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Banner
  }
}, {
  path: 'bannerList',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: BannerList
  }
}, {
  path: '/home',
  childRoutes: [{
    path: '*',
    childRoutes: [],
    component: NotFound
  }],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Home
  }
}];
// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];
const RouterMap = ({ store }) => (
  <Provider store={store}>
    <div>
      <AuthRoute history={hashHistory} location={location}></AuthRoute>
      <Router
        history={hashHistory}
        routes={[...autoGeneratedRoutes, ...customRoutes]}
      />
    </div>
  </Provider>
);
export default RouterMap
